spring:
  application:
    name: Lending
  datasource:
    url: jdbc:postgresql://localhost:5432/lmsdb
    username: lmsuser
    password: lmspass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true
        dialect: org.hibernate.dialect.PostgreSQLDialect  
app:
  constants:
    score-threshold: 500
    ws:
      url:
        customer: https://kycapitest.credable.io/service/customerWsdl.wsdl
    scoring-engine:
      client:
        url: https://scoringtest.credable.io/api/v1/client/createClient
      initiate-url: https://scoringtest.credable.io/api/v1/scoring/initiateQueryScore
      query-url: https://scoringtest.credable.io/api/v1/scoring/queryScore/
      token: 